theme: jekyll-theme-architect
title: GBittencourt Consulting
description: Home page da GBittencourt Consulting
show_downloads: false

# Google services
google_analytics: UA-97992983-2

# Jekyll plugins
plugins:
  - jekyll-redirect-from

langs:
- id: pt
  menu:
  - area: main
    label: Página principal
  - area: articles
    label: Artigos
  - area: contact
    label: Contato
- id: en
  menu:
  - area: main
    label: Home page
  - area: articles
    label: Articles
  - area: contact
    label: Contact
